### ISSUE TITLE
ANSI colors in prompt string

### ISSUE THREAD

**Issue by aleclarson** [antirez/linenoise#150]
I'm using https://github.com/hoelzro/lua-linenoise and noticed that the prompt string cannot contain non-printed characters without messing up tab completion, which must be due to incorrect string length calculation. My use case is ANSI coloring (256 spectrum).

https://github.com/hoelzro/lua-linenoise/issues/15

**Comment by hoelzro** [comment]
It's worth mentioning that readline gets around this by using `\001` and `\002` and "non-printable" markers: see `rl_expand_prompt` under https://tiswww.case.edu/php/chet/readline/readline.html

**Comment by aleclarson** [comment]
Closed in favor of #25

**Comment by hoelzro** [comment]
@aleclarson I would re-open this - I don't consider this a duplicate of #25.

On a side note: what GNU readline does for this is uses `\001` and `\002` to mark the parts of the string that shouldn't contribute to the prompt length: https://wiki.hackzine.org/development/misc/readline-color-prompt.html

**Comment by Sonophoto** [comment]
@hoelzro @aleclarson 

This is in fact an explicitly stated sub issue of #25 and I encourage you to read the discussion in full. Linenoise code isn't as abstracted as GNU Readline, that is by design.

This version of linenoise has multibyte and ANSI color Right Now in C++,  and works on windows too.

    https://github.com/yhirose/cpp-linenoise

If you need to use multibyte and ANSI in C then this one will work:
(Notice: It has several other modifications: https://github.com/antirez/linenoise/compare/master...Sonophoto:master

    https://github.com/Sonophoto/linenoise/blob/master/linenoise.c

ANSI color was an issue for me early on and that issue is resolved by the discussion in #25 and the corrected UTF-8 character counting implemented by @yhirose.
