### ISSUE TITLE
Newline (\n) not doing \r on Linux ($TERM = xterm)

### ISSUE THREAD

**Issue by thelamb** [antirez/linenoise#67]
I feel like I must be doing something wrong as I can't really imagine being the first to notice this behavior. So I apologize in advance if I'm just being silly here.

I'm using linenoise in a multi-threaded application that accepts user-input on terminal but can also output text on its own (for example, in case of errors it prints an error message).
We used to use libreadline, but it's no longer possible because of its license.

The error messages are just printed as:

```
std::cout << "Line one\n";
std::cout << "Line two\n";
```

With linenoise, the output is as follows:

```
Line one
        Line two
```

So 'Line two' is on a new line, but it starts right after 'Line one', rather than at the beginning of the line. It is as if the implicit \r is missing.
It's solved by using "\r\n" instead of \n as newline but it's kind of awkward to change this all over the place.

Note: clearly, whenever something is printed as a result of user-input, everything is fine. e.g.

```
> help
No problem
with newlines
here
```

Is this a known issue? Can I work around it without having to sed all of my \n into \r\n?

Thank you for your time.

**Comment by hlprasu** [comment]
Instead of fixing output behaviour in other parts of code, we can do the following -
1. Set output mode to not raw by default.
2. Change the output mode to raw just before actual printing. Then, switch it back to not raw mode as illustrated in the patch below.

I recently created a patch in the connection on https://github.com/msteveb/linenoise/pull/18

It was easy to do in that branch as the print function was wrapped in as a custom function fd_printf()

**Comment by hlprasu** [comment]
I haven't tried termbox. I don't know about the possibility of this
conflict.

In my code (without termbox), I am using linenoise with this patch, and so
far it has worked satisfactorily.

~ Prasad Bhat

**Comment by sgbeal** [comment]
My utmost apologies - i was crosswiring two projects. i've deleted my comment about termbox.
